title: vRuby LMS
email: your-email@example.com
description: >-
  vRuby LMS - Microsoft Learn–style learning platform
baseurl: "/Learning-Paths"      # <= EXACTLY your repo name
url: "https://lavanya-d19.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation (optional)
# navigation:
#   - title: "Home"
#     url: "/"
#   - title: "Learning Paths"
#     url: "/LearningPaths/"
#   - title: "Onboarding"
#     url: "/Onboarding/"
#   - title: "Resources"
#     url: "/LearningPaths/README.md"

# Exclude these files/folders from build
exclude:
  - node_modules
  - vendor
  - README.md
  - .github
  - .vscode
