name: Onboarding Checklist
description: Track your onboarding progress step by step
title: "Onboarding - [Your Name]"
labels: ["onboarding"]
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome! 🎉
        This is your personal onboarding tracker. Tick the boxes as you go.

  - type: checkboxes
    id: setup
    attributes:
      label: "📌 Setup"
      description: "Complete your initial setup tasks"
      options:
        - label: "Read the Welcome Message & Vision"
        - label: "Watch the Company Intro video"
        - label: "Join Discord & Introduce yourself"
        - label: "Create GitHub account & star this repo"
        - label: "Set up VS Code + extensions"

  - type: checkboxes
    id: lms
    attributes:
      label: "📚 LMS Basics"
      options:
        - label: "Open ‘How to Use ChatGPT & Copilot’ guide"
        - label: "Submit Week 1: Weekly Progress form"
        - label: "Complete Module 1 Quiz"
        - label: "Read Policies (rules, timings, holidays)"

  - type: textarea
    id: blockers
    attributes:
      label: "Blockers / Questions"
      description: "Anything slowing you down?"
      placeholder: "List blockers here"
